# Generated by Django 4.1.1 on 2025-01-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='null', max_length=120),
            preserve_default=False,
        ),
    ]
