# Generated by Django 4.1.1 on 2025-01-27 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Orders', '0002_orderheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('prov_order_number', models.CharField(max_length=20)),
                ('family', models.CharField(max_length=20)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('missing_elem', models.CharField(blank=True, max_length=40, null=True)),
                ('product', models.CharField(max_length=60)),
                ('in_sn', models.CharField(blank=True, max_length=20, null=True)),
                ('client', models.CharField(blank=True, max_length=30, null=True)),
                ('seller', models.CharField(blank=True, max_length=30, null=True)),
                ('reason', models.CharField(max_length=60)),
                ('cig', models.CharField(blank=True, max_length=6, null=True)),
                ('observations', models.CharField(blank=True, max_length=200, null=True)),
                ('out_sn', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice', models.CharField(blank=True, max_length=20, null=True)),
                ('order_number', models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
