# Generated by Django 4.1.1 on 2025-02-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderheader',
            name='order_stage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordercontent',
            name='family',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordercontent',
            name='order_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ordercontent',
            name='product',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='ordercontent',
            name='reason',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='ordercontent',
            name='user_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='order_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='tracking',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='user_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
