# Generated by Django 4.1.1 on 2025-02-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_orderheader_order_stage_alter_ordercontent_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercontent',
            name='prov_order_number',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='prov_order_number',
            field=models.CharField(max_length=25),
        ),
    ]
