# Generated by Django 4.1.1 on 2025-02-01 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_alter_ordercontent_prov_order_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderContent',
        ),
    ]
