# Generated by Django 4.1.1 on 2025-02-08 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0009_ordercontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderheader',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderContent',
        ),
        migrations.DeleteModel(
            name='OrderHeader',
        ),
    ]
