# Generated by Django 4.1.1 on 2025-02-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0012_orderheader_visible_alter_orderheader_order_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_nr',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
