# Generated by Django 4.1.1 on 2025-02-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0014_alter_orderheader_order_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderheader',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
