# Generated by Django 4.1.1 on 2025-02-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0015_orderheader_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercontent',
            name='subcat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
